export declare const DocumentProjectionNode: {
    new (latestValues?: import("../..").ResolvedValues, parent?: import("./types.js").IProjectionNode | undefined): {
        id: number;
        animationId: number;
        animationCommitId: number;
        instance: Window | undefined;
        root: import("./types.js").IProjectionNode;
        parent?: import("./types.js").IProjectionNode;
        path: import("./types.js").IProjectionNode[];
        children: Set<import("./types.js").IProjectionNode<unknown>>;
        options: import("./types.js").ProjectionNodeOptions;
        snapshot: import("./types.js").Measurements | undefined;
        layout: import("./types.js").Measurements | undefined;
        targetLayout?: import("sognaflow-utils").Box;
        layoutCorrected: import("sognaflow-utils").Box;
        targetDelta?: import("sognaflow-utils").Delta;
        target?: import("sognaflow-utils").Box;
        relativeTarget?: import("sognaflow-utils").Box;
        relativeTargetOrigin?: import("sognaflow-utils").Box;
        relativeParent?: import("./types.js").IProjectionNode;
        isTreeAnimating: boolean;
        isAnimationBlocked: boolean;
        attemptToResolveRelativeTarget?: boolean;
        targetWithTransforms?: import("sognaflow-utils").Box;
        prevProjectionDelta?: import("sognaflow-utils").Delta;
        projectionDelta?: import("sognaflow-utils").Delta;
        projectionDeltaWithTransform?: import("sognaflow-utils").Delta;
        scroll?: import("./types.js").ScrollMeasurements;
        isLayoutDirty: boolean;
        isProjectionDirty: boolean;
        isSharedProjectionDirty: boolean;
        isTransformDirty: boolean;
        updateManuallyBlocked: boolean;
        updateBlockedByResize: boolean;
        isUpdating: boolean;
        isSVG: boolean;
        needsReset: boolean;
        shouldResetTransform: boolean;
        hasCheckedOptimisedAppear: boolean;
        treeScale: import("sognaflow-utils").Point;
        resumeFrom?: import("./types.js").IProjectionNode;
        resumingFrom?: import("./types.js").IProjectionNode;
        latestValues: import("../..").ResolvedValues;
        eventHandlers: Map<import("./types.js").LayoutEvents, import("sognaflow-utils").SubscriptionManager<any>>;
        nodes?: import("../..").FlatTree;
        depth: number;
        prevTransformTemplateValue: string | undefined;
        preserveOpacity?: boolean;
        hasTreeAnimated: boolean;
        layoutVersion: number;
        addEventListener(name: import("./types.js").LayoutEvents, handler: any): VoidFunction;
        notifyListeners(name: import("./types.js").LayoutEvents, ...args: any): void;
        hasListeners(name: import("./types.js").LayoutEvents): boolean;
        mount(instance: Window): void;
        unmount(): void;
        blockUpdate(): void;
        unblockUpdate(): void;
        isUpdateBlocked(): boolean;
        isTreeAnimationBlocked(): boolean;
        startUpdate(): void;
        getTransformTemplate(): import("../..").TransformTemplate | undefined;
        willUpdate(shouldNotifyListeners?: boolean): void;
        updateScheduled: boolean;
        update(): void;
        scheduleUpdate: () => void;
        didUpdate(): void;
        clearAllSnapshots(): void;
        projectionUpdateScheduled: boolean;
        scheduleUpdateProjection(): void;
        scheduleCheckAfterUnmount(): void;
        checkUpdateFailed: () => void;
        updateProjection: () => void;
        updateSnapshot(): void;
        updateLayout(): void;
        updateScroll(phase?: import("./types.js").Phase): void;
        resetTransform(): void;
        measure(removeTransform?: boolean): {
            animationId: number;
            measuredBox: import("sognaflow-utils").Box;
            layoutBox: import("sognaflow-utils").Box;
            latestValues: {};
            source: number;
        };
        measurePageBox(): import("sognaflow-utils").Box;
        removeElementScroll(box: import("sognaflow-utils").Box): import("sognaflow-utils").Box;
        applyTransform(box: import("sognaflow-utils").Box, transformOnly?: boolean, output?: import("sognaflow-utils").Box): import("sognaflow-utils").Box;
        removeTransform(box: import("sognaflow-utils").Box): import("sognaflow-utils").Box;
        setTargetDelta(delta: import("sognaflow-utils").Delta): void;
        setOptions(options: import("./types.js").ProjectionNodeOptions): void;
        clearMeasurements(): void;
        forceRelativeParentToResolveTarget(): void;
        resolvedRelativeTargetAt: number;
        resolveTargetDelta(forceRecalculation?: boolean): void;
        getClosestProjectingParent(): import("./types.js").IProjectionNode<unknown> | undefined;
        isProjecting(): boolean;
        linkedParentVersion: number;
        createRelativeTarget(relativeParent: import("./types.js").IProjectionNode, layout: import("sognaflow-utils").Box, parentLayout: import("sognaflow-utils").Box): void;
        removeRelativeTarget(): void;
        hasProjected: boolean;
        calcProjection(): void;
        isVisible: boolean;
        hide(): void;
        show(): void;
        scheduleRender(notifyAll?: boolean): void;
        createProjectionDeltas(): void;
        animationValues?: import("../..").ResolvedValues;
        pendingAnimation?: import("../..").Process;
        currentAnimation?: import("../..").JSAnimation<number>;
        mixTargetDelta: (progress: number) => void;
        animationProgress: number;
        setAnimationOrigin(delta: import("sognaflow-utils").Delta, hasOnlyRelativeTargetChanged?: boolean): void;
        sognaflowValue?: import("../..").SognaflowValue<number>;
        startAnimation(options: import("../..").ValueAnimationOptions<number>): void;
        completeAnimation(): void;
        finishAnimation(): void;
        applyTransformsToTarget(): void;
        sharedNodes: Map<string, import("../..").NodeStack>;
        registerSharedNode(layoutId: string, node: import("./types.js").IProjectionNode): void;
        isLead(): boolean;
        getLead(): import("./types.js").IProjectionNode<unknown> | /*elided*/ any;
        getPrevLead(): import("./types.js").IProjectionNode<unknown> | undefined;
        getStack(): import("../..").NodeStack | undefined;
        promote({ needsReset, transition, preserveFollowOpacity, }?: {
            needsReset?: boolean;
            transition?: import("../..").Transition;
            preserveFollowOpacity?: boolean;
        }): void;
        relegate(): boolean;
        resetSkewAndRotation(): void;
        applyProjectionStyles(targetStyle: any, styleProp?: import("../..").SognaflowStyle): void;
        clearSnapshot(): void;
        resetTree(): void;
    };
};
