import { type ComponentType, type ReactNode, type ClipboardEvent, type CSSProperties } from "react"
import type { UIMessage, ChatStatus } from "ai"

/** Theme JSON generated by the playground */
export interface ChatTheme {
  theme: Record<string, string>
  light: Record<string, string>
  dark: Record<string, string>
}

/** Per-element CSS class overrides */
export interface ChatClassNames {
  root: string
  messageList: string
  userMessage: string
  assistantMessage: string
  inputBar: string
  sendButton: string
  stopButton: string
  toolBash: string
  toolEdit: string
  toolSearch: string
  toolTodo: string
  toolPlan: string
  toolTask: string
  toolMcp: string
  toolGeneric: string
}

/** Component slot overrides */
export interface ChatSlots {
  InputBar: ComponentType<any>
  UserMessage: ComponentType<any>
  AssistantMessage: ComponentType<any>
  ToolRenderer: ComponentType<any>
  MessageActions: ComponentType<any>
}

/** Props for createAgentChat() */
export interface CreateAgentChatOptions {
  agent: string
  /** Provide either tokenUrl (simple) or getToken (full control) */
  tokenUrl?: string
  getToken?: () => Promise<string>
  apiUrl?: string
  /**
   * Sandbox ID — identifies the persistent sandbox environment.
   *
   * Each unique `sandboxId` maps to its own sandbox (isolated VM with persistent filesystem).
   * Requests with the same `sandboxId` share the same sandbox — files, git repos,
   * and session history persist across messages.
   *
   * If omitted, the relay creates a new sandbox per request.
   *
   * @example
   * // Per-user sandbox
   * createAgentChat({ agent: "my-agent", tokenUrl: "/api/an/token", sandboxId: `user-${userId}` })
   *
   * // Continue existing sandbox
   * createAgentChat({ agent: "my-agent", tokenUrl: "/api/an/token", sandboxId: sandbox.id })
   */
  sandboxId?: string
  /**
   * Thread ID — identifies a specific conversation thread within the sandbox.
   * Requires `sandboxId` to be set. If omitted with `sandboxId`, creates a new thread.
   */
  threadId?: string
  onFinish?: () => void
  onError?: (error: Error) => void
}

/** Props passed to custom tool renderer components */
export interface CustomToolRendererProps {
  name: string
  input: Record<string, unknown>
  output: unknown | undefined
  status: "pending" | "streaming" | "success" | "error"
}

/** A model option for the model selector */
export interface ModelOption {
  id: string
  name: string
  version?: string
}

/** Props for the <AgentChat> drop-in component */
export interface AgentChatProps {
  messages: UIMessage[]
  onSend: (message: { role: "user"; content: string }) => void
  status: ChatStatus
  onStop: () => void
  error?: Error

  theme?: ChatTheme
  colorMode?: "light" | "dark" | "auto"

  classNames?: Partial<ChatClassNames>
  slots?: Partial<ChatSlots>
  toolRenderers?: Record<string, ComponentType<CustomToolRendererProps>>

  /** Show window chrome header (traffic lights + agent indicator) */
  showWindowChrome?: boolean

  /** Model selector configuration */
  modelSelector?: {
    models: ModelOption[]
    activeModelId?: string
    onModelChange?: (id: string) => void
    display?: "popover" | "badge"
    position?: "left" | "right"
  }

  /** Mode selector configuration */
  modeSelector?: {
    modes: { id: string; label: string; icon?: ReactNode }[]
    activeMode?: string
    onModeChange?: (id: string) => void
    display?: "inline" | "popover"
  }

  /** Attachment configuration */
  attachments?: {
    onAttach?: () => void
    images?: { id: string; filename: string; url: string; size?: number }[]
    files?: { id: string; filename: string; size?: number }[]
    onRemoveImage?: (id: string) => void
    onRemoveFile?: (id: string) => void
    onPaste?: (e: ClipboardEvent) => void
    isDragOver?: boolean
  }

  className?: string
  style?: CSSProperties
}

// Legacy type aliases kept for compatibility.
export type AnTheme = ChatTheme
export type AnClassNames = ChatClassNames
export type AnSlots = ChatSlots
export type CreateAnChatOptions = CreateAgentChatOptions
export type AnModelOption = ModelOption
export type AnAgentChatProps = AgentChatProps
